"""prod

Revision ID: 00ce81b9f1d6
Revises: 9b28fd9cc178
Create Date: 2023-09-09 15:36:55.438102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ce81b9f1d6'
down_revision = '9b28fd9cc178'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
