"""testing

Revision ID: 1ca27a9118f4
Revises: d97fb1dd24f6
Create Date: 2023-09-06 20:55:51.566196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca27a9118f4'
down_revision = 'd97fb1dd24f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
