"""prod

Revision ID: 223e213d576f
Revises: 74298de1e0a1
Create Date: 2023-09-09 15:39:17.002431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223e213d576f'
down_revision = '74298de1e0a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('functions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('functions', schema=None) as batch_op:
        batch_op.drop_column('execution_count')

    # ### end Alembic commands ###
