"""dev

Revision ID: 41e1453ab5e7
Revises: f033b565ada0
Create Date: 2023-08-25 13:11:24.857116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e1453ab5e7'
down_revision = 'f033b565ada0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
