"""prod

Revision ID: 74298de1e0a1
Revises: 00ce81b9f1d6
Create Date: 2023-09-09 15:37:42.893756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74298de1e0a1'
down_revision = '00ce81b9f1d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
