"""automatic revision

Revision ID: 8f147f5df4ea
Revises: 7b2ee66113f9
Create Date: 2023-11-10 12:54:26.830824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f147f5df4ea'
down_revision = '7b2ee66113f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
