"""default message

Revision ID: 9b28fd9cc178
Revises: b8abafdbd280
Create Date: 2023-09-09 15:00:03.664547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b28fd9cc178'
down_revision = 'b8abafdbd280'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('functions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('functions', schema=None) as batch_op:
        batch_op.drop_column('execution_count')

    # ### end Alembic commands ###
