"""testing

Revision ID: d97fb1dd24f6
Revises: d8b735a15d5c
Create Date: 2023-09-06 20:55:29.708408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97fb1dd24f6'
down_revision = 'd8b735a15d5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
