"""dev

Revision ID: f033b565ada0
Revises: 2fdc2caa50ba
Create Date: 2023-08-25 13:09:54.406450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f033b565ada0'
down_revision = '2fdc2caa50ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('function_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_time', sa.Integer(), nullable=True))
        batch_op.drop_column('execution_time')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('function_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_time', sa.INTEGER(), nullable=True))
        batch_op.drop_column('completion_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
